name = aliveworld_bridge_mcl
title = AliveWorld Mineclonia Bridge
description = Compatibility bridge for Mineclonia/VoxeLibre-like games.
author = mirivlad
depends = aliveworld_core
optional_depends = mcl_core, mcl_mobs, mcl_villages, mcl_structures
