# Identity
server_name = AliveWorld Test
server_description = AliveWorld на Luanti/Mineclonia.
motd = Добро пожаловать в AliveWorld.

# Network
port = 30000
server_announce = false

# Gameplay
creative_mode = false
enable_damage = true
enable_pvp = false

# Players
name = mirivlad
default_privs = interact, shout

# Server behavior
max_users = 10
enable_rollback_recording = true

# Logs
debug_log_level = action
