name = aliveworld_test_suite
title = AliveWorld Test Suite
description = Test suite for AliveWorld mods using Luanti TestKit
author = mirivlad
depends = luanti_testkit
optional_depends = aliveworld_core, aliveworld_player, aliveworld_world, aliveworld_bridge_mcl, aliveworld_admin
