name = luanti_testkit
title = Luanti TestKit
description = Universal server-side test framework for Luanti mods
author = mirivlad
optional_depends = aliveworld_core, aliveworld_player, aliveworld_world
